import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { AppClientProvider } from "@/components";

const nunitoSans = Nunito({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.className}`}>
        <AppClientProvider>
          {children}
        </AppClientProvider>
      </body>
    </html>
  );
}
